services: mongodb
language: node_js
node_js:
- '5.11'
addons:
  code_climate:
    repo_token: a5a45b680accbcfdb426fe83d1ee0a017859bb6bd894788f39649331ba747797
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
deploy:
 provider: heroku
 on: master
 app: uniritter-node-2016-delio
  api_key:
    secure: o7rLYibZtQC9vFTUAK5xklLPPHCSpcZIcE+qkUPeZqaXOf6wT/XsF+5RMjuhwuLVxfAdJn5lZonAkEeiZjlBgcXrPOhJ2qzudmqFGR50K3iW84kKkZyCEOMd8i56DS9Z1/dPOIU4i7dPPxpNDCi5SnTnmUUPpFuDWVZP0IY5SdDtuUCItQbpAmz7QpmpFqW4yAs0yMtx/kxp8E03dD0NKcYBu3j3w9KDGD7L8M2sGBvBlAy7+v4l415IWX6gM94DERkdgv6F0jO/n14PLfv/NjVsNfW+XKzFPM719LrzJy8nnRNJtsxspXoq7ZEgxhTRAVcO8SR6dGc8FNd5q3DwbclcCj6ORI9SXcw1HOQaYJ8ACJgS/3/feq/kkhy+84pJBQMhcjM6TLLj/6W4DvU1dyDbwN4Bgf8/68DF504HbEDlU8PKI5DZa8fQ3UdUq11O1q87VwPfKtyyMGnWXA6BSCjZ/KCPlE+oDn9udGFkL18U+P+kEyZ5YdumnflTTJoLb0lGvN/JlBEskVp95slh/MH8kIJ9zwrb/jlqgrBbK31MOB8o5fbk3qlx6Rv0Xo4k5dtKzUUrhDaWllg5EF1vHtWUKtGymL4X/gmjMrThYLL5r52oU37wZ7TDkNQS7ZUZ+yDScJQscvLbPjpm6+/Her+NVso13R6es7eDgFNSl6g=
