services: mongodb
language: node_js
node_js:
  - "5.11"
addons:
    code_climate:
        repo_token: a5a45b680accbcfdb426fe83d1ee0a017859bb6bd894788f39649331ba747797
after_script:
 - npn install -g code_climate-test-reporter
 - codeclimate-test-reporter < coverage/lcov.info
 
